name: C++ with Static Libcurl (Multi-platform)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # Use a matrix strategy to run jobs on different operating systems
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Checks out your repository under $GITHUB_WORKSPACE

    # --- Windows Compilation Steps ---
    - name: Install MSYS2 and required libs (Windows)
      if: matrix.os == 'windows-latest'
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64 # Use the Universal C Runtime 64-bit environment
        update: true
        install: >-
          mingw-w64-ucrt-x86_64-toolchain
          mingw-w64-ucrt-x86_64-curl
          mingw-w64-ucrt-x86_64-openssl
          mingw-w64-ucrt-x86_64-zlib
          mingw-w64-ucrt-x86_64-libidn2
          mingw-w64-ucrt-x86_64-libssh2
          mingw-w64-ucrt-x86_64-libpsl
          mingw-w64-ucrt-x86_64-brotli
          mingw-w64-ucrt-x86_64-zstd
          mingw-w64-ucrt-x86_64-nghttp2
          mingw-w64-ucrt-x86_64-nghttp3
          mingw-w64-ucrt-x86_64-ngtcp2
          mingw-w64-ucrt-x86_64-libiconv
          mingw-w64-ucrt-x86_64-libunistring
          perl
        shell: bash {0} # Set the shell to msys2 bash for subsequent steps

    - name: Compile on Windows
      if: matrix.os == 'windows-latest'
      run: |
        # Prepend MSYS2 bin directory to PATH to ensure its pkg-config is found first
        export PATH="/ucrt64/bin:$PATH"
        
        echo "Current PATH after prepend: $PATH"
        echo "Attempting to locate pkg-config:"
        which pkg-config
        ls -l /ucrt64/bin/pkg-config || echo "/ucrt64/bin/pkg-config not found or accessible"

        # Rely on the PATH for pkg-config
        PKG_CONFIG_CMD="pkg-config"

        echo "Using pkg-config command: $(which ${PKG_CONFIG_CMD})"
        ${PKG_CONFIG_CMD} --version # Verify pkg-config is found and runs

        # Get args required for compilation with pkg-config for both cflags (includes) and libs
        CURL_CFLAGS=$(${PKG_CONFIG_CMD} --define-prefix --static --cflags libcurl)
        CURL_LIBS=$(${PKG_CONFIG_CMD} --define-prefix --static --libs libcurl)
        echo "CURL_CFLAGS: $CURL_CFLAGS" # For debugging purposes
        echo "CURL_LIBS: $CURL_LIBS" # For debugging purposes

        # Compile main.cpp and util.c into tt.exe
        # Added CURL_CFLAGS to ensure include paths are found
        g++ main.cpp util.c -o tt.exe -static -DCURL_STATICLIB ${CURL_CFLAGS} ${CURL_LIBS} -std=c++17

        # Compile setup.cpp into tt-setup.exe
        g++ setup.cpp -o tt-setup.exe -static -std=c++17
      shell: bash {0} # Ensure we're in the MSYS2 bash shell for these commands

    # --- Linux and macOS Compilation Steps ---
    - name: Install build tools (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt update
        sudo apt install -y build-essential make

    - name: Install build tools (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install gcc make openldap # Install openldap for LDAP symbols if libcurl insists on them
        brew link --force openldap # Force link to ensure it's in expected paths

    - name: Download, configure, and build libcurl (Linux/macOS)
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      run: |
        CURL_VERSION="8.7.1" # Using a specific stable version for reproducibility
        CURL_TARBALL="curl-${CURL_VERSION}.tar.gz"
        CURL_DIR="curl-${CURL_VERSION}"
        INSTALL_DIR="${HOME}/curl" # User's specified installation directory

        mkdir -p "${INSTALL_DIR}" # Create the installation directory
        
        # Download libcurl source
        curl -LO "https://curl.se/download/${CURL_TARBALL}"
        tar -xzf "${CURL_TARBALL}" # Extract the source
        cd "${CURL_DIR}" # Navigate into the extracted source directory

        # Configure libcurl with the *full* set of disable/without flags from your documentation.
        # This is the most aggressive way to ensure a minimal libcurl without unwanted dependencies.
        # Warnings about unrecognized options are expected for some flags with newer curl versions.
        ./configure \
          --prefix="${INSTALL_DIR}" \
          --disable-shared \
          --enable-static \
          --disable-ftp \
          --disable-file \
          --disable-ldap \
          --disable-ldaps \
          --disable-rtsp \
          --disable-dict \
          --disable-telnet \
          --disable-tftp \
          --disable-pop3 \
          --disable-imap \
          --disable-smtp \
          --disable-gopher \
          --disable-smb \
          --disable-unix-sockets \
          --disable-verbose \
          --disable-ntlm-wb \
          --disable-tls-srp \
          --disable-threaded-resolver \
          --disable-libcurl-option \
          --disable-alt-svc \
          --disable-doh \
          --disable-hsts \
          --disable-http-proxy \
          --disable-metalink \
          --disable-mqtt \
          --disable-proxy \
          --disable-rtmp \
          --disable-sspi \
          --disable-websockets \
          --disable-pthreads \
          --disable-manual \
          --disable-ipv6 \
          --without-brotli \
          --without-zstd \
          --without-nghttp2 \
          --without-libidn2 \
          --without-libpsl \
          --without-libssh2 \
          --without-gnutls \
          --without-librtmp \
          --without-mbedtls \
          --without-nss \
          --without-openssl \
          --without-winldap \
          --without-wincrypt \
          --without-schannel \
          --without-ca-bundle \
          --without-ca-path \
          --disable-netrc
        
        make # Compile libcurl
        make install # Install libcurl to the specified prefix
        
        echo "--- Contents of installed curl directory ---"
        ls -R "${INSTALL_DIR}" # List installed files for debugging
        echo "------------------------------------------"
      working-directory: ${{ github.workspace }} # Ensure we start in the repo root

    - name: Compile main.cpp and util.c (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        INSTALL_DIR="${HOME}/curl"
        # Added -lzstd to link against the Zstd library for Linux
        g++ main.cpp util.c -o tt -L "${INSTALL_DIR}/lib" -I "${INSTALL_DIR}/include" -lcurl -DCURL_STATICLIB -static -static-libstdc++ -static-libgcc -std=c++17 -lzstd

    - name: Compile setup.cpp (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        g++ setup.cpp -o tt-setup -static -std=c++17 # Added -std=c++17 for consistency

    - name: Compile main.cpp and util.c (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        # Add Homebrew paths to ensure correct g++ and other tools are found
        # For Apple Silicon Macs (M1/M2/M3)
        export PATH="/opt/homebrew/bin:$PATH"
        # For Intel Macs
        export PATH="/usr/local/bin:$PATH"

        # Explicitly use g++-13 (or the latest GCC version installed by Homebrew)
        # This ensures we're using the GNU compiler, not Apple Clang, for consistent C++17 support.
        # If g++-13 isn't found, this will fall back to g++ which might still be clang.
        GXX_CMD="g++-13"
        if ! command -v "$GXX_CMD" &> /dev/null; then
            echo "Warning: g++-13 not found, falling back to default g++."
            GXX_CMD="g++"
        fi

        echo "Using g++ command: $GXX_CMD" # For debugging
        $GXX_CMD --version # Print g++ version for debugging

        INSTALL_DIR="${HOME}/curl"
        # Explicitly link against OpenLDAP libraries and macOS frameworks
        $GXX_CMD main.cpp util.c -o tt \
          -L "${INSTALL_DIR}/lib" -I "${INSTALL_DIR}/include" \
          -lcurl -DCURL_STATICLIB -std=c++17 \
          -L"$(brew --prefix openldap)/lib" -lldap -lber \
          -framework CoreFoundation -framework SystemConfiguration -lz

    - name: Compile setup.cpp (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        # Explicitly use g++-13 (or the latest GCC version installed by Homebrew)
        GXX_CMD="g++-13"
        if ! command -v "$GXX_CMD" &> /dev/null; then
            echo "Warning: g++-13 not found, falling back to default g++."
            GXX_CMD="g++"
        fi
        
        # Added -std=c++17 to ensure modern C++ features are enabled for setup.cpp
        $GXX_CMD setup.cpp -o tt-setup -std=c++17

    # --- Remove Run Compiled Applications Step ---
    # Removed the step to run compiled executables as requested.

    - name: Verify compiled files (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        ls -l tt.exe
        ls -l tt-setup.exe
      shell: bash {0}

    - name: Verify compiled files (Linux/macOS)
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      run: |
        ls -l tt
        ls -l tt-setup
